-- Schema-only foundation for one longitudinal clinical record per patient.
-- The BIGINT identity is an intentional exception to the repository's UUID
-- primary keys; JavaScript-facing boundaries must preserve it as a decimal string.
-- created_/updated_ columns follow AUD-001 nullable actor bookkeeping. They are
-- not an immutable event log, and updated_* remain NULL until explicitly set.
-- src/db/migrate.ts owns the per-file transaction and migration ledger.

CREATE TABLE clinical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE NO ACTION,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES users(id),
  updated_at TIMESTAMPTZ,
  CONSTRAINT clinical_records_patient_id_unique UNIQUE (patient_id)
);
